# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PredictBinaryForSingleimage.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_predict_binary_single(object):
    def setupUi(self, Dialog_predict_binary_single):
        Dialog_predict_binary_single.setObjectName("Dialog_predict_binary_single")
        Dialog_predict_binary_single.resize(472, 339)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_predict_binary_single)
        self.buttonBox.setGeometry(QtCore.QRect(30, 290, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog_predict_binary_single)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 160, 441, 27))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_5.setMinimumSize(QtCore.QSize(55, 23))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.lineEdit_model = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_model.setMinimumSize(QtCore.QSize(201, 23))
        self.lineEdit_model.setObjectName("lineEdit_model")
        self.horizontalLayout_7.addWidget(self.lineEdit_model)
        self.pushButton_model = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_model.setMinimumSize(QtCore.QSize(0, 23))
        self.pushButton_model.setObjectName("pushButton_model")
        self.horizontalLayout_7.addWidget(self.pushButton_model)
        self.layoutWidget = QtWidgets.QWidget(Dialog_predict_binary_single)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 444, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.spinBox_bands = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_bands.sizePolicy().hasHeightForWidth())
        self.spinBox_bands.setSizePolicy(sizePolicy)
        self.spinBox_bands.setMinimumSize(QtCore.QSize(47, 22))
        self.spinBox_bands.setMinimum(1)
        self.spinBox_bands.setMaximum(1000)
        self.spinBox_bands.setProperty("value", 3)
        self.spinBox_bands.setObjectName("spinBox_bands")
        self.horizontalLayout_4.addWidget(self.spinBox_bands)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.comboBox_dtype = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_dtype.setObjectName("comboBox_dtype")
        self.comboBox_dtype.addItem("")
        self.comboBox_dtype.addItem("")
        self.comboBox_dtype.addItem("")
        self.comboBox_dtype.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_dtype)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(33, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.spinBox_windsize = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(23)
        sizePolicy.setHeightForWidth(self.spinBox_windsize.sizePolicy().hasHeightForWidth())
        self.spinBox_windsize.setSizePolicy(sizePolicy)
        self.spinBox_windsize.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_windsize.setMaximumSize(QtCore.QSize(50, 23))
        self.spinBox_windsize.setMaximum(1000)
        self.spinBox_windsize.setSingleStep(2)
        self.spinBox_windsize.setProperty("value", 256)
        self.spinBox_windsize.setObjectName("spinBox_windsize")
        self.horizontalLayout_4.addWidget(self.spinBox_windsize)
        self.layoutWidget_5 = QtWidgets.QWidget(Dialog_predict_binary_single)
        self.layoutWidget_5.setGeometry(QtCore.QRect(0, 80, 451, 65))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_network = QtWidgets.QGroupBox(self.layoutWidget_5)
        self.groupBox_network.setMinimumSize(QtCore.QSize(0, 63))
        self.groupBox_network.setMaximumSize(QtCore.QSize(16777215, 66))
        self.groupBox_network.setObjectName("groupBox_network")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_network)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.radioButton_unet = QtWidgets.QRadioButton(self.groupBox_network)
        self.radioButton_unet.setChecked(True)
        self.radioButton_unet.setObjectName("radioButton_unet")
        self.horizontalLayout_10.addWidget(self.radioButton_unet)
        self.radioButton_fcnnet = QtWidgets.QRadioButton(self.groupBox_network)
        self.radioButton_fcnnet.setObjectName("radioButton_fcnnet")
        self.horizontalLayout_10.addWidget(self.radioButton_fcnnet)
        self.radioButton_segnet = QtWidgets.QRadioButton(self.groupBox_network)
        self.radioButton_segnet.setObjectName("radioButton_segnet")
        self.horizontalLayout_10.addWidget(self.radioButton_segnet)
        self.horizontalLayout_3.addWidget(self.groupBox_network)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.layoutWidget_5)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 63))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 66))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.comboBox_target_class = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_target_class.setObjectName("comboBox_target_class")
        self.comboBox_target_class.addItem("")
        self.comboBox_target_class.addItem("")
        self.comboBox_target_class.addItem("")
        self.comboBox_target_class.addItem("")
        self.comboBox_target_class.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_target_class)
        self.horizontalLayout_3.addWidget(self.groupBox_5)
        self.layoutWidget_3 = QtWidgets.QWidget(Dialog_predict_binary_single)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 441, 27))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_6.setMinimumSize(QtCore.QSize(55, 23))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.lineEdit_image = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_image.setMinimumSize(QtCore.QSize(201, 23))
        self.lineEdit_image.setObjectName("lineEdit_image")
        self.horizontalLayout_8.addWidget(self.lineEdit_image)
        self.pushButton_image = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_image.setMinimumSize(QtCore.QSize(0, 23))
        self.pushButton_image.setObjectName("pushButton_image")
        self.horizontalLayout_8.addWidget(self.pushButton_image)
        self.layoutWidget_4 = QtWidgets.QWidget(Dialog_predict_binary_single)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 240, 441, 27))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_7.setMinimumSize(QtCore.QSize(55, 23))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.lineEdit_mask = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_mask.setMinimumSize(QtCore.QSize(201, 23))
        self.lineEdit_mask.setObjectName("lineEdit_mask")
        self.horizontalLayout_9.addWidget(self.lineEdit_mask)
        self.pushButton_mask = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_mask.setMinimumSize(QtCore.QSize(0, 23))
        self.pushButton_mask.setObjectName("pushButton_mask")
        self.horizontalLayout_9.addWidget(self.pushButton_mask)
        self.widget = QtWidgets.QWidget(Dialog_predict_binary_single)
        self.widget.setGeometry(QtCore.QRect(8, 200, 445, 24))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.comboBox_gupid = QtWidgets.QComboBox(self.widget)
        self.comboBox_gupid.setMinimumSize(QtCore.QSize(0, 22))
        self.comboBox_gupid.setObjectName("comboBox_gupid")
        self.comboBox_gupid.addItem("")
        self.comboBox_gupid.addItem("")
        self.comboBox_gupid.addItem("")
        self.comboBox_gupid.addItem("")
        self.comboBox_gupid.addItem("")
        self.comboBox_gupid.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_gupid)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.comboBox_strategy = QtWidgets.QComboBox(self.widget)
        self.comboBox_strategy.setMinimumSize(QtCore.QSize(0, 22))
        self.comboBox_strategy.setObjectName("comboBox_strategy")
        self.comboBox_strategy.addItem("")
        self.comboBox_strategy.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_strategy)

        self.retranslateUi(Dialog_predict_binary_single)
        self.buttonBox.rejected.connect(Dialog_predict_binary_single.reject)
        self.pushButton_image.clicked.connect(Dialog_predict_binary_single.slot_select_img_file)
        self.pushButton_model.clicked.connect(Dialog_predict_binary_single.slot_select_model_file)
        self.pushButton_mask.clicked.connect(Dialog_predict_binary_single.slot_save_mask_path)
        self.buttonBox.accepted.connect(Dialog_predict_binary_single.slot_ok)
        QtCore.QMetaObject.connectSlotsByName(Dialog_predict_binary_single)

    def retranslateUi(self, Dialog_predict_binary_single):
        _translate = QtCore.QCoreApplication.translate
        Dialog_predict_binary_single.setWindowTitle(_translate("Dialog_predict_binary_single", "Dialog"))
        self.label_5.setText(_translate("Dialog_predict_binary_single", "Model:"))
        self.pushButton_model.setText(_translate("Dialog_predict_binary_single", "Open"))
        self.label_8.setText(_translate("Dialog_predict_binary_single", "bands:"))
        self.label_9.setText(_translate("Dialog_predict_binary_single", "dtype:"))
        self.comboBox_dtype.setItemText(0, _translate("Dialog_predict_binary_single", "uint8"))
        self.comboBox_dtype.setItemText(1, _translate("Dialog_predict_binary_single", "uint10"))
        self.comboBox_dtype.setItemText(2, _translate("Dialog_predict_binary_single", "uint16"))
        self.comboBox_dtype.setItemText(3, _translate("Dialog_predict_binary_single", "float"))
        self.label_3.setText(_translate("Dialog_predict_binary_single", "windsize :"))
        self.groupBox_network.setTitle(_translate("Dialog_predict_binary_single", "Network"))
        self.radioButton_unet.setText(_translate("Dialog_predict_binary_single", "Unet"))
        self.radioButton_fcnnet.setText(_translate("Dialog_predict_binary_single", "Fcnnet"))
        self.radioButton_segnet.setText(_translate("Dialog_predict_binary_single", "Segnet"))
        self.groupBox_5.setTitle(_translate("Dialog_predict_binary_single", "Class"))
        self.label_2.setText(_translate("Dialog_predict_binary_single", "Target:"))
        self.comboBox_target_class.setItemText(0, _translate("Dialog_predict_binary_single", "roads"))
        self.comboBox_target_class.setItemText(1, _translate("Dialog_predict_binary_single", "buildings"))
        self.comboBox_target_class.setItemText(2, _translate("Dialog_predict_binary_single", "vegetation"))
        self.comboBox_target_class.setItemText(3, _translate("Dialog_predict_binary_single", "water"))
        self.comboBox_target_class.setItemText(4, _translate("Dialog_predict_binary_single", "else"))
        self.label_6.setText(_translate("Dialog_predict_binary_single", "Image:"))
        self.pushButton_image.setText(_translate("Dialog_predict_binary_single", "Open"))
        self.label_7.setText(_translate("Dialog_predict_binary_single", "Output mask:"))
        self.pushButton_mask.setText(_translate("Dialog_predict_binary_single", "Open"))
        self.label_10.setText(_translate("Dialog_predict_binary_single", "GPU ID:"))
        self.comboBox_gupid.setItemText(0, _translate("Dialog_predict_binary_single", "0"))
        self.comboBox_gupid.setItemText(1, _translate("Dialog_predict_binary_single", "1"))
        self.comboBox_gupid.setItemText(2, _translate("Dialog_predict_binary_single", "2"))
        self.comboBox_gupid.setItemText(3, _translate("Dialog_predict_binary_single", "3"))
        self.comboBox_gupid.setItemText(4, _translate("Dialog_predict_binary_single", "4"))
        self.comboBox_gupid.setItemText(5, _translate("Dialog_predict_binary_single", "5"))
        self.checkBox.setText(_translate("Dialog_predict_binary_single", "Onehot"))
        self.label_11.setText(_translate("Dialog_predict_binary_single", "Predict strategy:"))
        self.comboBox_strategy.setItemText(0, _translate("Dialog_predict_binary_single", "original"))
        self.comboBox_strategy.setItemText(1, _translate("Dialog_predict_binary_single", "smooth"))

