# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageClip.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_image_clip(object):
    def setupUi(self, Dialog_image_clip):
        Dialog_image_clip.setObjectName("Dialog_image_clip")
        Dialog_image_clip.resize(483, 288)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_image_clip)
        self.buttonBox.setGeometry(QtCore.QRect(180, 250, 281, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog_image_clip)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 170, 461, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 441, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(65, 22))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_output = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_output.setMinimumSize(QtCore.QSize(201, 22))
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.gridLayout.addWidget(self.lineEdit_output, 0, 1, 1, 1)
        self.pushButton_output = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_output.setMinimumSize(QtCore.QSize(0, 22))
        self.pushButton_output.setObjectName("pushButton_output")
        self.gridLayout.addWidget(self.pushButton_output, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog_image_clip)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 461, 151))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 441, 131))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setMinimumSize(QtCore.QSize(55, 0))
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lineEdit_input = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_input.setMinimumSize(QtCore.QSize(201, 0))
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.horizontalLayout_4.addWidget(self.lineEdit_input)
        self.pushButton_input = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_input.setObjectName("pushButton_input")
        self.horizontalLayout_4.addWidget(self.pushButton_input)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setMinimumSize(QtCore.QSize(33, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox_x = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_x.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_x.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spinBox_x.setMaximum(100000)
        self.spinBox_x.setObjectName("spinBox_x")
        self.horizontalLayout_3.addWidget(self.spinBox_x)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setMinimumSize(QtCore.QSize(55, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.spinBox_y = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_y.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_y.setMaximum(100000)
        self.spinBox_y.setObjectName("spinBox_y")
        self.horizontalLayout_3.addWidget(self.spinBox_y)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.spinBox_column = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_column.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spinBox_column.setMinimum(1)
        self.spinBox_column.setMaximum(1000000000)
        self.spinBox_column.setSingleStep(10)
        self.spinBox_column.setObjectName("spinBox_column")
        self.horizontalLayout.addWidget(self.spinBox_column)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.spinBox_row = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_row.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spinBox_row.setMinimum(1)
        self.spinBox_row.setMaximum(1000000000)
        self.spinBox_row.setSingleStep(10)
        self.spinBox_row.setObjectName("spinBox_row")
        self.horizontalLayout.addWidget(self.spinBox_row)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_2.raise_()
        self.buttonBox.raise_()
        self.groupBox.raise_()

        self.retranslateUi(Dialog_image_clip)
        self.buttonBox.accepted.connect(Dialog_image_clip.slot_ok)
        self.buttonBox.rejected.connect(Dialog_image_clip.reject)
        self.pushButton_input.clicked.connect(Dialog_image_clip.slot_input)
        self.pushButton_output.clicked.connect(Dialog_image_clip.slot_output)
        QtCore.QMetaObject.connectSlotsByName(Dialog_image_clip)

    def retranslateUi(self, Dialog_image_clip):
        _translate = QtCore.QCoreApplication.translate
        Dialog_image_clip.setWindowTitle(_translate("Dialog_image_clip", "Clip image"))
        self.groupBox_2.setTitle(_translate("Dialog_image_clip", "Output parameters"))
        self.label_2.setText(_translate("Dialog_image_clip", "Output file"))
        self.pushButton_output.setText(_translate("Dialog_image_clip", "Open"))
        self.groupBox.setTitle(_translate("Dialog_image_clip", "Input parameters"))
        self.label.setText(_translate("Dialog_image_clip", "Input file"))
        self.pushButton_input.setText(_translate("Dialog_image_clip", "Open"))
        self.label_3.setText(_translate("Dialog_image_clip", "x :"))
        self.label_4.setText(_translate("Dialog_image_clip", "y :"))
        self.label_6.setText(_translate("Dialog_image_clip", "columns:"))
        self.label_5.setText(_translate("Dialog_image_clip", "rows:"))

