# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageStretch.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_image_stretch(object):
    def setupUi(self, Dialog_image_stretch):
        Dialog_image_stretch.setObjectName("Dialog_image_stretch")
        Dialog_image_stretch.resize(421, 265)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_image_stretch)
        self.buttonBox.setGeometry(QtCore.QRect(240, 230, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(Dialog_image_stretch)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 401, 151))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 386, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(55, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_input.setMinimumSize(QtCore.QSize(201, 0))
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.horizontalLayout.addWidget(self.lineEdit_input)
        self.pushButton_input = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_input.setObjectName("pushButton_input")
        self.horizontalLayout.addWidget(self.pushButton_input)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox_nodata = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_nodata.setMinimum(0)
        self.spinBox_nodata.setMaximum(1000000000)
        self.spinBox_nodata.setProperty("value", 65535)
        self.spinBox_nodata.setObjectName("spinBox_nodata")
        self.horizontalLayout_3.addWidget(self.spinBox_nodata)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.comboBox_outbits = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_outbits.setModelColumn(0)
        self.comboBox_outbits.setObjectName("comboBox_outbits")
        self.comboBox_outbits.addItem("")
        self.comboBox_outbits.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_outbits)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.spinBox_range = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_range.setMinimum(255)
        self.spinBox_range.setMaximum(1000000000)
        self.spinBox_range.setSingleStep(1)
        self.spinBox_range.setProperty("value", 1024)
        self.spinBox_range.setObjectName("spinBox_range")
        self.horizontalLayout_5.addWidget(self.spinBox_range)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.spinBox_cutvalue = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_cutvalue.setMaximum(10000000)
        self.spinBox_cutvalue.setProperty("value", 100)
        self.spinBox_cutvalue.setObjectName("spinBox_cutvalue")
        self.horizontalLayout_6.addWidget(self.spinBox_cutvalue)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog_image_stretch)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 170, 401, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 381, 24))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setMinimumSize(QtCore.QSize(65, 22))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_output = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_output.setMinimumSize(QtCore.QSize(201, 22))
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.horizontalLayout_2.addWidget(self.lineEdit_output)
        self.pushButton_output = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_output.setMinimumSize(QtCore.QSize(0, 22))
        self.pushButton_output.setObjectName("pushButton_output")
        self.horizontalLayout_2.addWidget(self.pushButton_output)

        self.retranslateUi(Dialog_image_stretch)
        self.buttonBox.rejected.connect(Dialog_image_stretch.reject)
        self.pushButton_output.clicked.connect(Dialog_image_stretch.slot_select_output_dir)
        self.pushButton_input.clicked.connect(Dialog_image_stretch.slot_select_input_dir)
        self.buttonBox.accepted.connect(Dialog_image_stretch.slot_ok)
        QtCore.QMetaObject.connectSlotsByName(Dialog_image_stretch)

    def retranslateUi(self, Dialog_image_stretch):
        _translate = QtCore.QCoreApplication.translate
        Dialog_image_stretch.setWindowTitle(_translate("Dialog_image_stretch", "Stetch image"))
        self.groupBox.setTitle(_translate("Dialog_image_stretch", "Input parameters"))
        self.label.setText(_translate("Dialog_image_stretch", "Input Dir"))
        self.pushButton_input.setText(_translate("Dialog_image_stretch", "Open"))
        self.label_3.setText(_translate("Dialog_image_stretch", "NoData:"))
        self.label_5.setText(_translate("Dialog_image_stretch", "Out bits:"))
        self.comboBox_outbits.setItemText(0, _translate("Dialog_image_stretch", "16 bits"))
        self.comboBox_outbits.setItemText(1, _translate("Dialog_image_stretch", "8 bits"))
        self.label_6.setText(_translate("Dialog_image_stretch", "Stretch Range:"))
        self.label_4.setText(_translate("Dialog_image_stretch", "Cut Value:"))
        self.groupBox_2.setTitle(_translate("Dialog_image_stretch", "Output parameters"))
        self.label_2.setText(_translate("Dialog_image_stretch", "Output Dir"))
        self.pushButton_output.setText(_translate("Dialog_image_stretch", "Open"))

