# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'label_check.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_label_check(object):
    def setupUi(self, Dialog_label_check):
        Dialog_label_check.setObjectName("Dialog_label_check")
        Dialog_label_check.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_label_check)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(Dialog_label_check)
        self.groupBox.setGeometry(QtCore.QRect(20, 100, 190, 66))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinBox_min = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_min.sizePolicy().hasHeightForWidth())
        self.spinBox_min.setSizePolicy(sizePolicy)
        self.spinBox_min.setMinimumSize(QtCore.QSize(47, 22))
        self.spinBox_min.setMinimum(0)
        self.spinBox_min.setObjectName("spinBox_min")
        self.horizontalLayout.addWidget(self.spinBox_min)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.spinBox_max = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_max.sizePolicy().hasHeightForWidth())
        self.spinBox_max.setSizePolicy(sizePolicy)
        self.spinBox_max.setMinimumSize(QtCore.QSize(47, 22))
        self.spinBox_max.setProperty("value", 2)
        self.spinBox_max.setObjectName("spinBox_max")
        self.horizontalLayout_2.addWidget(self.spinBox_max)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.widget = QtWidgets.QWidget(Dialog_label_check)
        self.widget.setGeometry(QtCore.QRect(20, 30, 366, 24))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(71, 22))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_inputpath = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_inputpath.sizePolicy().hasHeightForWidth())
        self.pushButton_inputpath.setSizePolicy(sizePolicy)
        self.pushButton_inputpath.setMinimumSize(QtCore.QSize(80, 22))
        self.pushButton_inputpath.setObjectName("pushButton_inputpath")
        self.gridLayout.addWidget(self.pushButton_inputpath, 0, 2, 1, 1)
        self.lineEdit_input = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_input.sizePolicy().hasHeightForWidth())
        self.lineEdit_input.setSizePolicy(sizePolicy)
        self.lineEdit_input.setMinimumSize(QtCore.QSize(201, 22))
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.gridLayout.addWidget(self.lineEdit_input, 0, 1, 1, 1)

        self.retranslateUi(Dialog_label_check)
        self.buttonBox.accepted.connect(Dialog_label_check.slot_ok)
        self.buttonBox.rejected.connect(Dialog_label_check.reject)
        self.pushButton_inputpath.clicked.connect(Dialog_label_check.slot_select_input_path)
        QtCore.QMetaObject.connectSlotsByName(Dialog_label_check)

    def retranslateUi(self, Dialog_label_check):
        _translate = QtCore.QCoreApplication.translate
        Dialog_label_check.setWindowTitle(_translate("Dialog_label_check", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog_label_check", "valid data"))
        self.label_2.setText(_translate("Dialog_label_check", "min"))
        self.label_3.setText(_translate("Dialog_label_check", "max"))
        self.label.setText(_translate("Dialog_label_check", "label image"))
        self.pushButton_inputpath.setText(_translate("Dialog_label_check", "Open"))

