# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AccuracyEvaluate.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_accuracy_evaluate(object):
    def setupUi(self, Dialog_accuracy_evaluate):
        Dialog_accuracy_evaluate.setObjectName("Dialog_accuracy_evaluate")
        Dialog_accuracy_evaluate.resize(488, 236)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_accuracy_evaluate)
        self.buttonBox.setGeometry(QtCore.QRect(70, 180, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget_4 = QtWidgets.QWidget(Dialog_accuracy_evaluate)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 50, 411, 27))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_8.setMinimumSize(QtCore.QSize(55, 23))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.lineEdit_mask = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_mask.setMinimumSize(QtCore.QSize(201, 23))
        self.lineEdit_mask.setObjectName("lineEdit_mask")
        self.horizontalLayout_9.addWidget(self.lineEdit_mask)
        self.pushButton_mask = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_mask.setMinimumSize(QtCore.QSize(0, 23))
        self.pushButton_mask.setObjectName("pushButton_mask")
        self.horizontalLayout_9.addWidget(self.pushButton_mask)
        self.layoutWidget_3 = QtWidgets.QWidget(Dialog_accuracy_evaluate)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 10, 411, 27))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_6.setMinimumSize(QtCore.QSize(55, 23))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.lineEdit_gt = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_gt.setMinimumSize(QtCore.QSize(201, 23))
        self.lineEdit_gt.setObjectName("lineEdit_gt")
        self.horizontalLayout_8.addWidget(self.lineEdit_gt)
        self.pushButton_gt = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_gt.setMinimumSize(QtCore.QSize(0, 23))
        self.pushButton_gt.setObjectName("pushButton_gt")
        self.horizontalLayout_8.addWidget(self.pushButton_gt)
        self.groupBox = QtWidgets.QGroupBox(Dialog_accuracy_evaluate)
        self.groupBox.setGeometry(QtCore.QRect(30, 80, 231, 80))
        self.groupBox.setObjectName("groupBox")
        self.spinBox_max = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_max.setGeometry(QtCore.QRect(180, 40, 47, 23))
        self.spinBox_max.setObjectName("spinBox_max")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 40, 41, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(130, 40, 41, 16))
        self.label_2.setObjectName("label_2")
        self.spinBox_min = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_min.setGeometry(QtCore.QRect(60, 40, 47, 23))
        self.spinBox_min.setObjectName("spinBox_min")
        self.label_3 = QtWidgets.QLabel(Dialog_accuracy_evaluate)
        self.label_3.setGeometry(QtCore.QRect(280, 120, 71, 16))
        self.label_3.setObjectName("label_3")
        self.doubleSpinBox_rate = QtWidgets.QDoubleSpinBox(Dialog_accuracy_evaluate)
        self.doubleSpinBox_rate.setGeometry(QtCore.QRect(360, 110, 51, 23))
        self.doubleSpinBox_rate.setMinimum(0.01)
        self.doubleSpinBox_rate.setMaximum(1.0)
        self.doubleSpinBox_rate.setSingleStep(0.01)
        self.doubleSpinBox_rate.setProperty("value", 0.5)
        self.doubleSpinBox_rate.setObjectName("doubleSpinBox_rate")

        self.retranslateUi(Dialog_accuracy_evaluate)
        self.buttonBox.rejected.connect(Dialog_accuracy_evaluate.reject)
        self.buttonBox.accepted.connect(Dialog_accuracy_evaluate.slot_ok)
        self.pushButton_gt.clicked.connect(Dialog_accuracy_evaluate.slot_select_gt_file)
        self.pushButton_mask.clicked.connect(Dialog_accuracy_evaluate.slot_select_mask_file)
        QtCore.QMetaObject.connectSlotsByName(Dialog_accuracy_evaluate)

    def retranslateUi(self, Dialog_accuracy_evaluate):
        _translate = QtCore.QCoreApplication.translate
        Dialog_accuracy_evaluate.setWindowTitle(_translate("Dialog_accuracy_evaluate", "Dialog"))
        self.label_8.setText(_translate("Dialog_accuracy_evaluate", "Predict mask:"))
        self.pushButton_mask.setText(_translate("Dialog_accuracy_evaluate", "Open"))
        self.label_6.setText(_translate("Dialog_accuracy_evaluate", "Ground Truth:"))
        self.pushButton_gt.setText(_translate("Dialog_accuracy_evaluate", "Open"))
        self.groupBox.setTitle(_translate("Dialog_accuracy_evaluate", "Values range"))
        self.label.setText(_translate("Dialog_accuracy_evaluate", "min:"))
        self.label_2.setText(_translate("Dialog_accuracy_evaluate", "max:"))
        self.label_3.setText(_translate("Dialog_accuracy_evaluate", "Check rate:"))

