# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SampleGenSelfAdapt.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_sampleGenSelfAdapt(object):
    def setupUi(self, Dialog_sampleGenSelfAdapt):
        Dialog_sampleGenSelfAdapt.setObjectName("Dialog_sampleGenSelfAdapt")
        Dialog_sampleGenSelfAdapt.resize(447, 332)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_sampleGenSelfAdapt)
        self.buttonBox.setGeometry(QtCore.QRect(240, 290, 181, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(Dialog_sampleGenSelfAdapt)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 437, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(55, 23))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_input.setMinimumSize(QtCore.QSize(201, 23))
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.horizontalLayout.addWidget(self.lineEdit_input)
        self.pushButton_input = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_input.setMinimumSize(QtCore.QSize(0, 23))
        self.pushButton_input.setObjectName("pushButton_input")
        self.horizontalLayout.addWidget(self.pushButton_input)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 66))
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.spinBox_min = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_min.sizePolicy().hasHeightForWidth())
        self.spinBox_min.setSizePolicy(sizePolicy)
        self.spinBox_min.setMinimumSize(QtCore.QSize(47, 22))
        self.spinBox_min.setMinimum(0)
        self.spinBox_min.setObjectName("spinBox_min")
        self.horizontalLayout_6.addWidget(self.spinBox_min)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.spinBox_max = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_max.sizePolicy().hasHeightForWidth())
        self.spinBox_max.setSizePolicy(sizePolicy)
        self.spinBox_max.setMinimumSize(QtCore.QSize(47, 22))
        self.spinBox_max.setProperty("value", 2)
        self.spinBox_max.setObjectName("spinBox_max")
        self.horizontalLayout_7.addWidget(self.spinBox_max)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.horizontalLayout_11.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 66))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.radioButton_binary = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_binary.setChecked(True)
        self.radioButton_binary.setObjectName("radioButton_binary")
        self.horizontalLayout_10.addWidget(self.radioButton_binary)
        self.radioButton_multiclass = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_multiclass.setObjectName("radioButton_multiclass")
        self.horizontalLayout_10.addWidget(self.radioButton_multiclass)
        self.horizontalLayout_11.addWidget(self.groupBox_4)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(33, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox_windsize = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(23)
        sizePolicy.setHeightForWidth(self.spinBox_windsize.sizePolicy().hasHeightForWidth())
        self.spinBox_windsize.setSizePolicy(sizePolicy)
        self.spinBox_windsize.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_windsize.setMaximumSize(QtCore.QSize(50, 23))
        self.spinBox_windsize.setMinimum(32)
        self.spinBox_windsize.setMaximum(1000)
        self.spinBox_windsize.setSingleStep(4)
        self.spinBox_windsize.setProperty("value", 480)
        self.spinBox_windsize.setObjectName("spinBox_windsize")
        self.horizontalLayout_3.addWidget(self.spinBox_windsize)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_targetLabel = QtWidgets.QLabel(self.layoutWidget)
        self.label_targetLabel.setMinimumSize(QtCore.QSize(50, 30))
        self.label_targetLabel.setObjectName("label_targetLabel")
        self.horizontalLayout_2.addWidget(self.label_targetLabel)
        self.spinBox_targetLabel = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_targetLabel.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_targetLabel.setMinimum(1)
        self.spinBox_targetLabel.setProperty("value", 1)
        self.spinBox_targetLabel.setObjectName("spinBox_targetLabel")
        self.horizontalLayout_2.addWidget(self.spinBox_targetLabel)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(33, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.doubleSpinBox_sampleScale = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_sampleScale.setMinimum(0.1)
        self.doubleSpinBox_sampleScale.setSingleStep(0.1)
        self.doubleSpinBox_sampleScale.setProperty("value", 1.0)
        self.doubleSpinBox_sampleScale.setObjectName("doubleSpinBox_sampleScale")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_sampleScale)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_12)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.checkBox_normimg = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_normimg.setObjectName("checkBox_normimg")
        self.horizontalLayout_9.addWidget(self.checkBox_normimg)
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_9.addWidget(self.checkBox)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(55, 23))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_15.addWidget(self.label_6)
        self.lineEdit_output = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_output.setMinimumSize(QtCore.QSize(201, 23))
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.horizontalLayout_15.addWidget(self.lineEdit_output)
        self.pushButton_output = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_output.setMinimumSize(QtCore.QSize(0, 23))
        self.pushButton_output.setObjectName("pushButton_output")
        self.horizontalLayout_15.addWidget(self.pushButton_output)
        self.verticalLayout.addLayout(self.horizontalLayout_15)

        self.retranslateUi(Dialog_sampleGenSelfAdapt)
        self.pushButton_input.clicked.connect(Dialog_sampleGenSelfAdapt.slot_input)
        self.radioButton_binary.clicked.connect(Dialog_sampleGenSelfAdapt.slot_strategy_binary)
        self.radioButton_multiclass.clicked.connect(Dialog_sampleGenSelfAdapt.slot_strategy_multiclass)
        self.pushButton_output.clicked.connect(Dialog_sampleGenSelfAdapt.slot_output)
        self.buttonBox.accepted.connect(Dialog_sampleGenSelfAdapt.slot_ok)
        self.buttonBox.rejected.connect(Dialog_sampleGenSelfAdapt.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_sampleGenSelfAdapt)

    def retranslateUi(self, Dialog_sampleGenSelfAdapt):
        _translate = QtCore.QCoreApplication.translate
        Dialog_sampleGenSelfAdapt.setWindowTitle(_translate("Dialog_sampleGenSelfAdapt", "sample generate selfAdapt"))
        self.label.setText(_translate("Dialog_sampleGenSelfAdapt", "Input Dir"))
        self.pushButton_input.setText(_translate("Dialog_sampleGenSelfAdapt", "Open"))
        self.groupBox.setTitle(_translate("Dialog_sampleGenSelfAdapt", "valid data"))
        self.label_8.setText(_translate("Dialog_sampleGenSelfAdapt", "min"))
        self.label_9.setText(_translate("Dialog_sampleGenSelfAdapt", "      max"))
        self.groupBox_4.setTitle(_translate("Dialog_sampleGenSelfAdapt", "Strategy"))
        self.radioButton_binary.setText(_translate("Dialog_sampleGenSelfAdapt", "Binary"))
        self.radioButton_multiclass.setText(_translate("Dialog_sampleGenSelfAdapt", "Multiclass"))
        self.label_3.setText(_translate("Dialog_sampleGenSelfAdapt", "     windsize :"))
        self.label_targetLabel.setText(_translate("Dialog_sampleGenSelfAdapt", "target label :"))
        self.label_4.setText(_translate("Dialog_sampleGenSelfAdapt", " sample scale:"))
        self.label_5.setText(_translate("Dialog_sampleGenSelfAdapt", "mode:"))
        self.checkBox_normimg.setText(_translate("Dialog_sampleGenSelfAdapt", "normalized_img"))
        self.checkBox.setText(_translate("Dialog_sampleGenSelfAdapt", "augment"))
        self.label_6.setText(_translate("Dialog_sampleGenSelfAdapt", "Save Dir"))
        self.pushButton_output.setText(_translate("Dialog_sampleGenSelfAdapt", "Open"))

